import{a as S,S as v,i as l}from"./assets/vendor-xpOxgMII.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",M="8147558-833d78601e58fec7a899b71a3";async function u(r,t){const s={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(q,{params:s})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),B=new v(".gallery a");function y(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:b,downloads:w})=>`
    <li class="gallery-item">
        <a href="${a}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${i}</p>
          <p><b>Comments</b> ${b}</p>
          <p><b>Downloads</b> ${w}</p>
        </div>
      </li> `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function $(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const P=document.querySelector(".search-form"),O=document.querySelector(".load-more");let c="",n=1,d=0;P.addEventListener("submit",x);O.addEventListener("click",A);async function x(r){if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!!c){n=1,E(),L(),p();try{const t=await u(c,n);if(t.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits),d=Math.ceil(t.totalHits/15),n<d&&$()}catch{l.error({message:"Something went wrong 😢"})}finally{g()}}}async function A(){n+=1,p();try{const r=await u(c,n);y(r.hits),_(),n>=d&&(L(),l.info({message:"We're sorry, but you've reached the end of search results."}))}catch{l.error({message:"Something went wrong 😢"})}finally{g()}}function _(){const r=document.querySelector(".photo-card");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
